name: Publish Python code on PyPI
description: >-
  Retrieves a release's source and binary distributions from GitHub
  Actions artifact storage and uploads them to the Python Package
  Index (PyPI) using
  [Trusted Publishing](https://docs.pypi.org/trusted-publishers/).
  The calling GitHub Actions workflow job **MUST** have permission to
  [fetch a JSON Web Token from GitHub's OpenID Connect provider](https://docs.github.com/en/actions/reference/security/oidc)
  (`id-token: write`) .

inputs:
  repository-url:
    description: >-
      The target package index, [TestPyPI](https://test.pypi.org/) by
      default.
    required: true
    default: https://test.pypi.org/legacy/

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v8.0.1
      with:
        merge-mutiple: true
    - uses: pypa/gh-action-pypi-publish@v1.13.0
      with:
        packages-dir: dist
        print-hash: true
        repository-url: ${{ inputs.repository-url }}
        verbose: true
