name: Test Python code
description: >-
  Runs pytest via GNU Make.  Installs Python and Google Chrome, along
  with the matching version of chromedriver.  The makefile targets
  `build-deps`, which runs as the superuser, and `test` **MUST**
  handle other test dependencies.  Supports
  [matrix strategies](https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations).

inputs:
  python-version:
    description: The version of Python with which to test.
    default: "3.12"
  requirements:
    description: >-
      Optional; the name of a workflow artifact containing Python
      package dependency pins.
    default: pip-compile-artifacts

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6.0.2
    - uses: actions/setup-python@v6.2.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
    - uses: browser-actions/setup-chrome@v2.1.1
      with:
        install-dependencies: true
        install-chromedriver: true
    - shell: bash
      run: sudo make build-deps
    - if: inputs.requirements
      uses: actions/download-artifact@v8.0.1
      with:
        name: ${{ inputs.requirements }}
    - shell: bash
      run: make test
