name: Lint code
description: >-
  Checks code syntax/style using the configured
  [pre-commit](https://pre-commit.com/) hooks.  Installs several
  common linter dependencies, including
  [OpenTofu](https://opentofu.org/),
  [pinact](https://github.com/suzuki-shunsuke/pinact/), and
  [Trivy](https://trivy.dev/).

inputs:
  access-app-id:
    description: >-
      Provide the app ID of a GitHub App used to access private
      repositories.  When
      [registering the app](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app)
      in the organization, disable webhook functionality and grant
      **read-only**
      [repository permissions for "Contents"](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps#repository-permissions-for-contents).
      After completing app registration,
      [generate a private key](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/managing-private-keys-for-github-apps)
      and install the app, giving it access to selected repositories
      as appropriate.
    required: false
    default: ~
  access-key:
    description: >-
      Log into the GitHub App used to access private repositories with
      this
      [private key](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/managing-private-keys-for-github-apps).
    required: false
    default: ~
  owner:
    description: >-
      Optionally access private OpenTofu modules in repositories owned
      by this GitHub account or organization, overriding
      [github.repository_owner](https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#github-context).
    required: false
    default: ~
  python-version:
    description: The version of Python with which to run pre-commit.
    required: true
    default: "3.13"

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install Python ${{ inputs.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
    - name: Install pre-commit
      shell: bash
      run: pip install -r "${GITHUB_ACTION_PATH}/requirements.txt" --require-hashes
    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2.0.0
      with:
        cache: true
        tofu_version: 1.11.5
    - name: Install TFLint
      uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
      with:
        cache: true
        tflint_version: v0.61.0
    - name: Install TFLint plugins
      if: hashFiles('.tflint.*')
      shell: bash
      run: tflint --init
    - name: Install pinact
      shell: bash
      run: |
        version=v3.9.0
        asset=pinact_linux_amd64.tar.gz
        bindir=$(mktemp -d)
        gh release download -R suzuki-shunsuke/pinact "$version" -p "$asset"
        gh attestation verify "$asset" \
            -R suzuki-shunsuke/pinact \
            --signer-workflow suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml
        tar -C "$bindir" -xzf "$asset" pinact
        rm "$asset"
        echo "$bindir" >> $GITHUB_PATH
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Install Trivy
      uses: aquasecurity/setup-trivy@3fb12ec12f41e471780db15c232d5dd185dcb514 # v0.2.6
      with:
        version: v0.69.3
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ inputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - id: private-repository-access
      if: inputs.access-app-id && inputs.access-key
      uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      with:
        app-id: ${{ inputs.access-app-id }}
        private-key: ${{ inputs.access-key }}
        owner: ${{ inputs.owner || github.repository_owner }}
    - if: steps.private-repository-access.outputs.token
      uses: de-vri-es/setup-git-credentials@5e1f18da68b7039c7f824408d170811aaec93ca8 # v2.1.2
      with:
        credentials: |
          https://x-access-token:${{ steps.private-repository-access.outputs.token }}@github.com/
    - shell: bash
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      env:
        GITHUB_TOKEN: ${{ steps.private-repository-access.outputs.token }}
