name: Pin Python project dependencies
description: >-
  Pins dependencies and stores them in a
  [GitHub Actions workflow artifact](https://docs.github.com/en/actions/concepts/workflows-and-actions/workflow-artifacts),
  an immutable archive, which facilitates reproducible builds.  Run
  this action after pre-commit in the same workflow job.

inputs:
  artifact-name:
    description: >-
      The name of the immutable archive that will contain the
      dependency pins.
    required: true
    default: pip-compile-artifacts

runs:
  using: composite
  steps:
    - name: Install pip-tools
      shell: bash
      run: pip install -r "${GITHUB_ACTION_PATH}/requirements.txt" --require-hashes
    - shell: bash
      run: pip-compile
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ${{ inputs.artifact-name }}
        path: requirements.txt
        if-no-files-found: error
